cc_test(
  name = "test",
  deps = [
    "@boost.test",
    "//stream-shell:stream-shell-lib",
    "@protobuf//:differencer",
  ],
  srcs = [
    "stream_parser_test.cpp",
    "tokenize_test.cpp",
  ],
)
